version: "3"
services:
  db:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: lizloang
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: dblmd
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: liz.loang@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "8080:80"
    depends_on:
      - db
volumes:
  pgdata:
